[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["school", "project"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = [
  "E","F","I","B","UP","N","S","W","C4","T20","RET","ARG","RUF"
]
ignore = ["E501"]

[tool.ruff.per-file-ignores]
"school/migrations/*" = ["E501"]
